<?xml version="1.0" encoding="UTF-8"?><testsuites>
  <testsuite name="main.tftest.hcl" tests="2" skipped="0" failures="1" errors="0">
    <testcase name="failing_assertion" classname="main.tftest.hcl" time="TIME_REDACTED" timestamp="TIMESTAMP_REDACTED">
      <failure message="Test run failed"></failure>
      <system-err><![CDATA[
Error: Test assertion failed

  on main.tftest.hcl line 3, in run "failing_assertion":
   3:     condition     = local.number < 0
    ├────────────────
    │ local.number is 10

local variable 'number' has a value greater than zero, so this assertion will
fail
]]></system-err>
    </testcase>
    <testcase name="passing_assertion" classname="main.tftest.hcl" time="TIME_REDACTED" timestamp="TIMESTAMP_REDACTED"></testcase>
  </testsuite>
</testsuites>